# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Capigo < Formula
  desc "CLI tool and Go SDK for the Capigo platform"
  homepage "https://capigo.app"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vtech-com/capigo-api-sdk/releases/download/v0.3.1/capigo_0.3.1_darwin_amd64.tar.gz"
      sha256 "f74875e90c41e741974161cb720a92432441730321bea7f8589a60a493fa680b"

      define_method(:install) do
        bin.install "capigo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vtech-com/capigo-api-sdk/releases/download/v0.3.1/capigo_0.3.1_darwin_arm64.tar.gz"
      sha256 "3ef5d77ed43b0f3adbb2634b58850fd184eeb9ad8f2c4576753914789e372e0d"

      define_method(:install) do
        bin.install "capigo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vtech-com/capigo-api-sdk/releases/download/v0.3.1/capigo_0.3.1_linux_amd64.tar.gz"
      sha256 "139d8a0a24c9c037fbb45729f7f0d78e3167fed9222ee2d30f33cee3580c4495"
      define_method(:install) do
        bin.install "capigo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vtech-com/capigo-api-sdk/releases/download/v0.3.1/capigo_0.3.1_linux_arm64.tar.gz"
      sha256 "9ccfaff19799523d1c3a8142868a17c9367d46a6857edea58c7bc5b9ce905782"
      define_method(:install) do
        bin.install "capigo"
      end
    end
  end
end
