# This file was generated by GoReleaser. DO NOT EDIT.
cask "capigo" do
  version "0.23.1"

  on_macos do
    on_intel do
      sha256 "4f29041295c79f1dbe45f74d397eaf10441b2a9f185fa7fe9f44b0a47302d463"
      url "https://github.com/vtech-com/capigo-api-sdk/releases/download/v#{version}/capigo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5a966468f73bcc3845c03332cbf93f6a54a2fb350d6195888d9770fbb752f64b"
      url "https://github.com/vtech-com/capigo-api-sdk/releases/download/v#{version}/capigo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0eecd999e2c24cff26a8f074dde0d669f65ea9d97847d89d47cfd17b5fc934e6"
      url "https://github.com/vtech-com/capigo-api-sdk/releases/download/v#{version}/capigo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "93f3cb7a0f3e726c79298b2c961b5326cc2780818020f4b231f1cec6f7d86556"
      url "https://github.com/vtech-com/capigo-api-sdk/releases/download/v#{version}/capigo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "capigo"
  desc "CLI tool and Go SDK for the Capigo platform"
  homepage "https://capigo.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "capigo"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/capigo"]
  end

  # No zap stanza required

end
