# This file was generated by GoReleaser. DO NOT EDIT.
cask "capigo" do
  version "0.15.0"

  on_macos do
    on_intel do
      sha256 "4378a0d8c5bdc625edcacd3dda7abd7d81b301e25d9b701ff18e4c264e273edd"
      url "https://github.com/vtech-com/capigo-api-sdk/releases/download/v#{version}/capigo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f889f83080ce6a0b562a33d12881e1909929f036c9f8f3631e2e488597eeeec8"
      url "https://github.com/vtech-com/capigo-api-sdk/releases/download/v#{version}/capigo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a571cc90883b682831e0e6d1533cc55bf7fbb9405471db35349e08f26ea74f2f"
      url "https://github.com/vtech-com/capigo-api-sdk/releases/download/v#{version}/capigo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8011108184f4840621d6c8546a2dd5497f62cf34b94d75b6425ba97b2245f012"
      url "https://github.com/vtech-com/capigo-api-sdk/releases/download/v#{version}/capigo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "capigo"
  desc "CLI tool and Go SDK for the Capigo platform"
  homepage "https://capigo.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "capigo"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/capigo"]
  end

  # No zap stanza required

end
