# This file was generated by GoReleaser. DO NOT EDIT.
cask "capigo" do
  version "0.20.0"

  on_macos do
    on_intel do
      sha256 "832997dd9ff91e1f74d1fb6c6d7f81c3ad8a6bd9d3ad2e88b29a1fd1f12ba3fd"
      url "https://github.com/vtech-com/capigo-api-sdk/releases/download/v#{version}/capigo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9594550f5abc1a822fa3fc2c4df80f41b4e9a733419659940e583168841d705c"
      url "https://github.com/vtech-com/capigo-api-sdk/releases/download/v#{version}/capigo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "106709517426436ec8ce222196d765daf07fd75d854088dc0d5ef8517af85fdb"
      url "https://github.com/vtech-com/capigo-api-sdk/releases/download/v#{version}/capigo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "812a98f650415fa26c9568ca131e38ad04a025c0ae176819ed8b8d2e6eec4995"
      url "https://github.com/vtech-com/capigo-api-sdk/releases/download/v#{version}/capigo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "capigo"
  desc "CLI tool and Go SDK for the Capigo platform"
  homepage "https://capigo.app"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "capigo"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/capigo"]
  end

  # No zap stanza required

end
